### ISSUE TITLE
超图GIS小工具

### ISSUE THREAD

**Issue by wsqstar** [DipperMap/dippermap#16]
### 站点名称

超图-GIS小工具

### 站点

https://www.supermapol.com/gistools/home

### 站点简介

超图的GIS在线工具平台。提供坐标，数据格式转换；地理编码；在线切图等功能。

### 站点英文介绍

SuperMap's GIS online tool platform. Provides functions such as coordinates and data format conversion, geocoding, and online map cutting.

### 图标

![ol_logo_blue 99efa04e](https://github.com/DipperMap/dippermap/assets/24500520/96b00efe-d3db-4921-b7fb-5b35ed86477c)

**Comment by lzxue** [comment]
暂时不添加了，需要登录，不能拿来即用
