### ISSUE TITLE
Natural Earth全球地图

### ISSUE THREAD

**Issue by viotbery** [DipperMap/dippermap#32]
### 站点名称

Natural Earth

### 站点

https://www.naturalearthdata.com/

### 站点简介

Natural Earth 是一个公共领域地图数据集，比例尺为 1:10m、1:50m 和 1:1.1亿。Natural Earth 将矢量数据和光栅数据紧密结合在一起，您可以使用制图或 GIS 软件制作各种视觉效果良好、制作精良的地图。

### 站点英文介绍

Natural Earth is a public domain map dataset available at 1:10m, 1:50m, and 1:110 million scales. Featuring tightly integrated vector and raster data, with Natural Earth you can make a variety of visually pleasing, well-crafted maps with cartography or GIS software.

### 图标

![image](https://github.com/DipperMap/dippermap/assets/64581887/f4f0776b-157d-4db3-9c65-071c95a3bf2b)

**Comment by wsqstar** [comment]
感谢！已经收录！https://nav.dippermap.com/?site=data
