### ISSUE TITLE
新增用户收藏卡片，展示用户关注站点

### ISSUE THREAD

**Issue by lzxue** [DipperMap/dippermap#60]
### 问题描述

当前站点比较多而全，用户更关注自己常用站点，需要增加收藏卡片和收藏功能。

- 主站增加一个收藏分组卡片，始终保持在第一位。
- 每个站点增加收藏功能，可以在站点卡片右上角增加收藏 icon 按钮
- 收藏数据存储在本地

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by wsqstar** [comment]
在纯前端的在线导航网站中实现用户喜好网站的收藏功能，你可以考虑以下几种解决方案：

1. **本地存储：** 使用浏览器的本地存储（localStorage或sessionStorage）来保存用户的收藏列表。这样用户可以在同一浏览器中保留他们的喜好网站，但请注意，这些数据是在用户的本地存储中，如果用户清除浏览器缓存或切换设备，这些收藏将丢失。

2. **账户系统：** 创建一个用户账户系统，允许用户注册和登录。通过用户账户，你可以将用户的收藏列表保存在服务器上，确保他们可以在不同设备上访问到。这需要一定的后端开发，包括数据库存储。

3. **同步到云服务：** 类似于账户系统，但是你可以选择使用第三方云服务（如Firebase、AWS Amplify等）来存储用户的收藏数据。这样用户可以在不同设备上同步他们的收藏，而无需自己管理账户系统。

4. **浏览器扩展：** 考虑开发浏览器扩展，使用户可以在任何网站上方便地添加收藏。扩展可以将用户的收藏数据存储在云端，以确保跨设备同步。

5. **使用第三方服务：** 利用第三方服务，例如Pocket、Evernote等，用户可以使用这些服务来管理他们的网址收藏。你的网站可以与这些服务集成，通过API来获取和保存用户的收藏数据。

6. **生成分享链接：** 让用户生成一个特殊的分享链接，包含他们的收藏列表。这个链接可以通过复制和粘贴分享给其他人或在不同设备上使用。这种方式不需要账户系统，但也意味着用户需要手动管理分享链接。

根据你的项目需求和技术能力，选择适合你的方案。如果你希望提供更好的用户体验，可能需要考虑一种结合本地存储和云服务的混合方案，以便用户在各种情况下都能访问他们的收藏。

**Comment by wsqstar** [comment]
目前已经实现收藏。
但是可能需要考虑
- 收藏全站同步，随着站点增加，收藏可能藏在某一个角落
- 收藏网站的保存
