### ISSUE TITLE
作为GIS工具类，怎么能没有turf.js的导航呢

### ISSUE THREAD

**Issue by 2448795365** [DipperMap/dippermap#72]
### 问题描述

turf.js 是地理空间分析库，处理各种地图算法。在GIS应用方面是很实用的工具类

### 平台

- 操作系统: [macOS, Windows, Linux, React Native ...]
- 网页浏览器: [Google Chrome, Safari, Firefox]

**Comment by lzxue** [comment]
其实有的

**Comment by lzxue** [comment]
https://nav.dippermap.com/?site=tech  藏的太深了，看来要做些减法看

**Comment by SevenNorth** [comment]
![image](https://github.com/DipperMap/dippermap/assets/53900832/678fd768-9963-4486-8f54-720089c0444f)

**Comment by 2448795365** [comment]
> https://nav.dippermap.com/?site=tech 藏的太深了，看来要做些减法看

恕我直言，要不是楼下那位给我截了个图，我都不知道左上角还有个切换功能，哈哈哈
