### ISSUE TITLE
收藏-是否全站统一？

### ISSUE THREAD

**Issue by wsqstar** [DipperMap/dippermap#79]
### 问题描述

收藏的目前是分站点的吗？

### 重现步骤

点击收藏，发现切换站点后没有数据，意识到收藏是分站点的。

### 预期行为

- 预期（待讨论）：
1. 所有站点的收藏通用，使用颜色/icon区分站点。
2. 还是说分开收藏

### 平台

- 操作系统:, Windows
- 网页浏览器: [Google Chrome

**Comment by lzxue** [comment]
统一好些，这样不需要多次切换了
